# Generated by Django 4.1.1 on 2022-12-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='country',
            new_name='Country',
        ),
    ]
